package vista;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Nicolas Diaz
 */
public class VtnRecibos extends javax.swing.JFrame {

    // SINGLETON - variable para control de instnacia de clase
    private static VtnRecibos instancia;

    // SINGLETON - Control de solo una instancia de clase
    public static VtnRecibos getInstancia() {
        if (instancia == null) {
            instancia = new VtnRecibos();
        }
        return instancia;
    }

    private VtnRecibos() {
        setVisible(false);
        setResizable(false);
        initComponents();
        DefaultTableModel modelo = (DefaultTableModel) tableEstudiantesRegistros.getModel();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jProgressBar1 = new javax.swing.JProgressBar();
        jPanel3 = new javax.swing.JPanel();
        btnSalir = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableEstudiantesRegistros = new javax.swing.JTable();
        btnActualizarRecibo = new javax.swing.JButton();
        btnEliminarRecibo = new javax.swing.JButton();
        btnAgregarRecibo = new javax.swing.JButton();
        txtFBuscarRecibos = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btnBuscarRecibos = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setBackground(new java.awt.Color(172, 49, 43));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Pagos", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 18))); // NOI18N
        jPanel3.setName(""); // NOI18N
        jPanel3.setPreferredSize(new java.awt.Dimension(838, 532));

        btnSalir.setBackground(new java.awt.Color(255, 255, 255));
        btnSalir.setForeground(new java.awt.Color(0, 0, 0));
        btnSalir.setText("Salir");

        tableEstudiantesRegistros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID Estudiante", "Nombre", "Grado", "ID Pago", "Descripcion", "Año", "Mes", "Estado", "Valor"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tableEstudiantesRegistros);

        btnActualizarRecibo.setText("Actualizar Recibo");

        btnEliminarRecibo.setText("Eliminar Recibo");

        btnAgregarRecibo.setText("Agregar Recibo");

        txtFBuscarRecibos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFBuscarRecibosActionPerformed(evt);
            }
        });

        jLabel1.setText("Buscar recibos de estudiante con codigo: ");

        btnBuscarRecibos.setText("Buscar Recibos Estudiante");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(btnSalir)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(122, 122, 122)
                .addComponent(btnAgregarRecibo, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(183, 183, 183)
                .addComponent(btnActualizarRecibo, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 146, Short.MAX_VALUE)
                .addComponent(btnEliminarRecibo, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel1)
                .addGap(36, 36, 36)
                .addComponent(txtFBuscarRecibos, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnBuscarRecibos)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFBuscarRecibos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(btnBuscarRecibos))
                .addGap(27, 27, 27)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAgregarRecibo, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnActualizarRecibo, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEliminarRecibo, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(btnSalir)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 1108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 668, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtFBuscarRecibosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFBuscarRecibosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFBuscarRecibosActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnActualizarRecibo;
    public javax.swing.JButton btnAgregarRecibo;
    public javax.swing.JButton btnBuscarRecibos;
    public javax.swing.JButton btnEliminarRecibo;
    public javax.swing.JButton btnSalir;
    private javax.swing.JLabel jLabel1;
    public javax.swing.JPanel jPanel3;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTable tableEstudiantesRegistros;
    public javax.swing.JTextField txtFBuscarRecibos;
    // End of variables declaration//GEN-END:variables

    /**
     * Metodo para generacion de ventanas emergentes, cada veentana depende una
     * clave que indica que ventana debe de ejecutarse
     *
     * @param claveVentanaEmergente
     */
    public static void mostrarJOptionPane(int claveVentanaEmergente) {
        // muestra ventanas dependiendo de la ocasion
        switch (claveVentanaEmergente) {
            case 0:
                JOptionPane.showMessageDialog(null, "No se pudo cargar el archivo properties.", "Incapacidad de Carga", 2);
                break;
            case 1:
                JOptionPane.showMessageDialog(null, "No se pudo realizar la consulta de la Base de Datos.", "Consulta de Base de Datos Incompleta", 2);
                break;
            case 2:
                JOptionPane.showMessageDialog(null, "Actualmente no existen registros de animales en la base de datos, por favor\n seleccione un archivo properties para cargar registros.", "Sin Registros", 2);
                break;
            case 3:
                JOptionPane.showMessageDialog(null, "No hay mas animales en la lista.", "Limite alcanzado", 2);
                break;
            case 4:
                JOptionPane.showMessageDialog(null, "No se pudo relizar el registro(s) de el(los) animal(es).", "Registro Incompleto", 2);
                break;
            case 5:
                JOptionPane.showMessageDialog(null, "No ha ingresado todos los datos, intente nuevamente.", "Ingreso Incompleto", 2);
                break;
            case 6:
                JOptionPane.showMessageDialog(null, "Se inserto registro(s) satisfactoriamente a la base de datos.", "Ingreso Completo", 2);
                break;
            case 7:
                JOptionPane.showMessageDialog(null, "No se pudo eliminar el animal", "Eliminacion no realizada", 2);
                break;
            case 8:
                JOptionPane.showMessageDialog(null, "Se elimino satisfactoriamente el animal", "Eliminacion realizada", 2);
                break;
            case 9:
                JOptionPane.showMessageDialog(null, "No se pudo modificar el animal", "Modificacion fallida", 2);
                break;
            case 10:
                JOptionPane.showMessageDialog(null, "Se modifico el animal", "Modificacion exitosa", 2);
                break;
            case 11:
                JOptionPane.showMessageDialog(null, "No se pudo guardar el archivo aleatorio", "Guardado Incompleto", 2);
                break;
        }

    }

}
